{{- range $name, $addon := .Values.addons }}
{{- if $addon.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: addon-{{ $name }}
  namespace: argocd
spec:
  destination:
    server: "https://kubernetes.default.svc" 
    namespace: {{ $addon.namespace }}
  project: default
  source:
    repoURL: {{ $addon.repoUrl }}
    chart: {{ $addon.chart }}
    targetRevision: {{ $addon.targetRevision }}
    helm:
      releaseName: {{ $addon.releaseName }}
      {{- with $addon.values }}
      valuesObject:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
{{- end }}
{{- end }}